// Catálogo e descrições de aptidões (dados usados pela UI da ficha).
// Separado do `actor-sheet.mjs` para reduzir o tamanho do arquivo principal.

export const APTIDOES_CATALOGO = {
  aura: {
    titulo: "Aura",
    entradas: [
      { key: "afinidadeAmpliada", label: "Afinidade Ampliada", description: "Ativa a aptidão Afinidade Ampliada." },
      { key: "auraAnuladora", label: "Aura Anuladora" },
      { key: "auraChamativa", label: "Aura Chamativa" },
      { key: "auraControlada", label: "Aura Controlada" },
      { key: "auraDeContencao", label: "Aura de Contenção" },
      { key: "auraDoBastiao", label: "Aura do Bastião" },
      { key: "auraDoComandante", label: "Aura do Comandante" },
      { key: "auraDoComandanteEvoluida", label: "Aura do Comandante Evoluída" },
      { key: "auraDrenadora", label: "Aura Drenadora" },
      { key: "auraElemental", label: "Aura Elemental" },
      { key: "auraReforcada", label: "Aura Reforçada" },
      { key: "auraImpenetravel", label: "Aura Impenetrável" },
      { key: "casuloDeEnergia", label: "Casulo de Energia" },
      { key: "auraElementalReforcada", label: "Aura Elemental Reforçada" },
      { key: "absorcaoElemental", label: "Absorção Elemental" },
      { key: "auraEmbacada", label: "Aura Embaçada" },
      { key: "auraInofensiva", label: "Aura Inofensiva" },
      { key: "auraExcessiva", label: "Aura Excessiva" },
      { key: "concentrarAura", label: "Concentrar Aura" },
      { key: "enganacaoProjetada", label: "Enganação Projetada" },
      { key: "golpeComAura", label: "Golpe com Aura" },
      { key: "transferenciaDeAura", label: "Transferência de Aura" },
      { key: "auraLacerante", label: "Aura Lacerante" },
      { key: "auraMacabra", label: "Aura Macabra" },
      { key: "auraMacica", label: "Aura Maciça" },
      { key: "auraMovedica", label: "Aura Movediça" },
      { key: "auraRedirecionada", label: "Aura Redirecionada" },
      { key: "pavorInstintivo", label: "Pavor Instintivo" },
      { key: "mimetismoDeResiduos", label: "Mimetismo de Resíduos" },
      { key: "auraCorrosiva", label: "Aura Corrosiva" },
      { key: "presencaEsmagadora", label: "Presença Esmagadora" }
    ]
  },
  controleELeitura: {
    titulo: "Controle e Leitura",
    entradas: [
      { key: "canalizarEmGolpe", label: "Canalizar em Golpe" },
      { key: "canalizacaoAvancada", label: "Canalização Avançada" },
      { key: "canalizacaoMaxima", label: "Canalização Máxima" },
      { key: "cobrirSe", label: "Cobrir-se" },
      { key: "coberturaAvancada", label: "Cobertura Avançada" },
      { key: "estimuloMuscular", label: "Estímulo Muscular" },
      { key: "estimuloMuscularAvancado", label: "Estímulo Muscular Avançado" },
      { key: "expandirAura", label: "Expandir Aura" },
      { key: "leituraDeAura", label: "Leitura de Aura" },
      { key: "leituraRapidaDeEnergia", label: "Leitura Rápida de Energia" },
      { key: "projetarEnergia", label: "Projetar Energia" },
      { key: "projecaoAvancada", label: "Projeção Avançada" },
      { key: "projecaoMaxima", label: "Projeção Máxima" },
      { key: "projecaoDividida", label: "Projeção Dividida" },
      { key: "punhoDivergente", label: "Punho Divergente" },
      { key: "emocaoDaPetalaDecadente", label: "Emoção da Pétala Decadente" },
      { key: "rastreioAvancado", label: "Rastreio Avançado" },
      { key: "regeneracaoEspontanea", label: "Regeneração Espontânea" },
      { key: "morfologiaGrotesca", label: "Morfologia Grotesca" },
      { key: "disparoDeNucleo", label: "Disparo de Núcleo" },
      { key: "sentidoDePredador", label: "Sentido de Predador" },
      { key: "divisaoCelular", label: "Divisão Celular" }
    ]
  },
  energiaReversa: {
    titulo: "Energia Reversa",
    entradas: [
      { key: "energiaReversa", label: "Energia Reversa" },
      { key: "curaAmplificada", label: "Cura Amplificada" },
      { key: "fluxoConstante", label: "Fluxo Constante" },
      { key: "regeneracaoAprimorada", label: "Regeneração Aprimorada" },
      { key: "liberacaoDeEnergiaReversa", label: "Liberação de Energia Reversa" },
      { key: "canalizarEmEnergiaReversa", label: "Canalizar em Energia Reversa" },
      { key: "curaEmGrupo", label: "Cura em Grupo" }
    ]
  },
  dominio: {
    titulo: "Domínio",
    entradas: [
      { key: "revestimentoDeDominio", label: "Revestimento de Domínio" },
      { key: "anularTecnica", label: "Anular Técnica" },
      { key: "expansaoDeDominioIncompleta", label: "Expansão de Domínio Incompleta" },
      { key: "expansaoDeDominioCompleta", label: "Expansão de Domínio Completa" },
      { key: "acertoGarantido", label: "Acerto Garantido" },
      { key: "expansaoDeDominioSemBarreiras", label: "Expansão de Domínio sem Barreiras" },
      { key: "ecoDoMedo", label: "Eco do Medo" },
      { key: "consumoDeEssencia", label: "Consumo de Essência" },
      { key: "ambienteMutavel", label: "Ambiente Mutável" }
    ]
  },
  barreiras: {
    titulo: "Barreiras",
    entradas: [
      { key: "tecnicasDeBarreiras", label: "Técnicas de Barreiras" },
      { key: "paredesResistentes", label: "Paredes Resistentes" },
      { key: "barreiraRapida", label: "Barreira Rápida" },
      { key: "cestaOcaDeVime", label: "Cesta Oca de Vime" },
      { key: "cortina", label: "Cortina" },
      { key: "barreiraOrganica", label: "Barreira Orgânica" },
      { key: "veloDeSombras", label: "Véu de Sombras" },
      { key: "dominioDeCaca", label: "Domínio de Caca" }
    ]
  },
  especiais: {
    titulo: "Especiais",
    entradas: [
      { key: "raioNegro", label: "Raio Negro" },
      { key: "abencoadoPelasFaiscasNegras", label: "Abençoado pelas Faíscas Negras" },
      { key: "dominioSimples", label: "Domínio Simples" },
      { key: "reversaoDeTecnica", label: "Reversão de Técnica" },
      { key: "tecnicaMaxima", label: "Técnica Máxima" },
      { key: "fisiologiaGrauEspecial", label: "Fisiologia de Grau Especial" },
      { key: "nucleoEnergiaErrante", label: "Núcleo de Energia Errante" },
      { key: "instintoPredadorAmaldicoado", label: "Instinto de Predador Amaldiçoado" },
      { key: "consumoDeEssenciaCanibalismo", label: "Consumo de Essência (Canibalismo)" },
      { key: "manifestacaoDeDesastre", label: "Manifestação de Desastre" },
      { key: "votoRestricaoFormaVerdadeira", label: "Voto de Restrição: Forma Verdadeira" },
      { key: "ressonanciaMedoColetivo", label: "Ressonância de Medo Coletivo" },
      { key: "regeneracaoCelularViolenta", label: "Regeneração Celular Violenta" },
      { key: "dominioDeIntrusao", label: "Domínio de Intrusão" },
      { key: "transcendenciaAmaldicoada", label: "Transcendência Amaldiçoada" }
    ]
  },
  // categoria nova para fisiologia específica de maldições
  fisiologiaAmaldicoada: {
    titulo: "Fisiologia Amaldiçoada",
    entradas: [
      { key: "nucleoMovel", label: "Núcleo Móvel" },
      { key: "parasitismoEnergetico", label: "Parasitismo Energético" },
      { key: "vozDasSombras", label: "Voz das Sombras" },
      { key: "adaptacaoReativa", label: "Adaptação Reativa" },
      { key: "almaMaldita", label: "Alma Maldita" },
      { key: "anatomiaIncompreensivel", label: "Anatomia Incompreensível" },
      { key: "armaNatural", label: "Arma Natural" },
      { key: "articulacoesExtensas", label: "Articulações Extensas" },
      { key: "bracosExtras", label: "Braços Extras" },
      { key: "capacidadeVoo", label: "Capacidade de Voo" },
      { key: "carapacaMutante", label: "Carapaça Mutante" },
      { key: "corpoEspecializado", label: "Corpo Especializado" },
      { key: "desenvolvimentoExagerado", label: "Desenvolvimento Exagerado" },
      { key: "devoradorDeEnergia", label: "Devorador de Energia" },
      { key: "instintoSanguinario", label: "Instinto Sanguinário" },
      { key: "olhosSombrios", label: "Olhos Sombrios" },
      { key: "pernasExtras", label: "Pernas Extras" },
      { key: "presencaNefasta", label: "Presença Nefasta" },
      { key: "sangueToxico", label: "Sangue Tóxico" }
    ]
  }
};

// Descrições específicas por categoria.chave — usadas para mostrar apenas a descrição
export const APTIDOES_DESCRICOES = {
  /* AURA */
  'aura.afinidadeAmpliada': 'Sua aura é aprimorada para ter uma maior afinidade com um elemento específico. Ao obter essa habilidade, você escolhe um tipo de dano elemental. Sempre que você infligir dano desse tipo específico, você causa dano adicional igual a 1 + o seu Nível de Aptidão em Aura no total de dano',
  'aura.auraAnuladora': 'A aura que o cobre obtém uma propriedade anuladora, capaz de protegê-lo de certos efeitos. Uma quantidade de vezes igual ao seu bônus de treinamento, caso você fosse sofrer uma condição, você pode pagar uma quantidade variável de energia para ignorá-la, a depender do nível da condição. Esta aptidão não pode anular manobras e efeitos físicos, como a ação Agarrar ou Ferimentos Complexos. Anular uma condição fraca custa 2PE; anular uma média custa 4PE; uma forte custa 6PE e uma extrema custa 10PE. Você recupera esses usos em um descanso longo.',
  'aura.auraChamativa': 'Você cria uma aura ao seu redor que é chamativa, atraente e mágica, cativando a atenção facilmente. Toda criatura que não for seu aliado, e começar um turno dentro de 4,5 metros de você, precisa realizar um teste de resistência de vontade (atributo principal da técnica). Em uma falha, ela fica enfeitiçada, podendo repetir o teste no próximo turno dela, deixando de estar enfeitiçada em um sucesso. Para cada vez que a criatura falhar no TR, ela recebe um bônus de +2 para resistir a esta aptidão ou deixar de estar enfeitiçada, até o final da cena. [Pré-Requisito: Presença 18 e Nível 6]',
  'aura.auraControlada': 'Você refinou seu controle sobre a aura, impedindo que ela se revele quando é inconveniente, ajudando-o a se ocultar e esconder sua presença. Você soma metade do seu Nível de Aptidão em Aura em testes de Furtividade. Sempre que realizar uma rolagem de Furtividade, você pode gastar 1 ponto de energia amaldiçoada para receber o seu nível de aptidão de aura por completo, ao invés de metade, controlando ainda mais a sua aura. [Pré-Requisito: Treinado em Furtividade e Destreza 16]',
  'aura.auraDeContencao': 'Com foco em conter, tem-se uma aura mais pesada e densa. Sempre que for agarrar um alvo, você adiciona metade do seu Nível de Aptidão em Aura na rolagem de Atletismo, assim como na rolagem para evitar que uma criatura escape. Uma quantidade de vezes por cena igual a metade do seu Nível de Aptidão em Aura, você pode também gastar 1 ponto de energia amaldiçoada para receber vantagem para agarrar ou impor desvantagem na criatura que tentar escapar. [Pré-Requisito: Força ou Constituição 16]',
  'aura.auraDoBastiao': 'Sua aura é protetiva e auxilia seus aliados a não serem acertados. Todo aliado dentro de 4,5 metros de você recebe um bônus na Defesa igual ao seu Nível de Aptidão em Aura.',
  'aura.auraDoComandante': 'Refletindo uma personalidade ou presença forte, estar coberto pela sua aura parece ser uma grande motivação para aliados. Você pode, como uma Ação Bônus, expandir sua aura para cobrir todo aliado dentro de 4,5 metros, os quais recebem 1 + metade do seu Nível de Aptidão em Aura em rolagens de dano e testes de perícia dentro do combate. Para cada turno que você manter a aura ativa, você paga 2 pontos de energia amaldiçoada. [PréRequisito: Presença 16 e Nível 8]',
  'aura.auraDoComandanteEvoluida': 'Sua presença como comandante se torna ainda mais forte e significante. Quando utilizar Aura do Comandante, você pode optar por somar seu Nível de Aptidão em Aura total ao invés de 1 + metade e, também, conceder um bônus de +2 em jogadas de ataques e TRs. Entretanto, o custo para manter aumenta de 2 para 4 PE. [Pré-Requisito: Aura do Comandante e Nível 12]',
  'aura.auraDrenadora': 'Uma aura vampiresca e capaz de drenar a partir da vida que é arrancada dos seus alvos. Sempre que matar um inimigo, você recebe PV temporários igual a Xd8 + seu modificador de Constituição, onde X é igual ao seu Nível de Aptidão em Aura. Eles podem acumular. [Pré-Requisito: Nível de Aptidão em Aura 2 e Nível 6]',
  'aura.auraElemental': 'Você converte as propriedades da sua aura, imbuindo-a com um elemento, para assim ser capaz de alterar o tipo de dano causado pelos seus ataques com armas. Ao obter essa habilidade, você pode escolher um tipo de dano da categoria Elementais para ser o novo tipo de dano dos seus ataques que não sejam de técnica amaldiçoada. Além disso, seus ataques causam 1d4 de dano adicional do tipo escolhido nesta aptidão. Com Nível de Aptidão em Aura 2, o dano adicional se torna 1d6; com nível de aptidão 3, se torna 1d8 e, com nível de aptidão 5, se torna 1d10. Dentro de combate, como uma ação livre, você pode desabilitar a aura elemental, retornando os seus ataques ao tipo de dano padrão. [Pré-Requisito: Nível 6]',
  'aura.auraElementalReforcada': 'Você reforça sua familiaridade com o elemento da sua aura, resistindo melhor a ele. Ao obter essa aptidão, você recebe RD ao tipo de dano da sua aura elemental igual a redução de Aura Reforçada somado ao seu Nível de Aptidão em Aura. [Pré-Requisito: Aura Elemental e Aura Reforçada]',
  'aura.absorcaoElemental': 'Uma aura pronta para absorver e armazenar elementos, podendo depois liberá-los em seus próprios ataques. Sempre que você receber dano elemental, você pode usar sua reação para absorver parte dele e guardar. Isso não reduz o dano, mas, na próxima vez em que você realizar um ataque você pode adicionar Xd6 de dano do mesmo tipo. X é igual ao seu Nível de Aptidão em Aura. Esta habilidade não é cumulativa. No Nível de Aptidão em Aura 3, o dado aumenta para d8; no nível 5, aumenta para d10. [Pré-Requisito: Aura Elemental]',
  'aura.auraEmbacada': 'Você desenvolve uma maneira de deixar a sua aura embaçada e borrada, criando uma chance de um ataque inimigo simplesmente errar. Como uma ação bônus, você pode pagar 2 pontos de energia amaldiçoada para ativar a aura embaçada, a qual você deve gastar 2 PE por rodada para manter, encerrando-se caso opte por não pagar. Enquanto a aura estiver ativa, todo ataque corpo-a-corpo ou a distância tem 20% de chance de falhar (1 ou 2 em 1d10). [Pré-Requisito: Nível 6]',
  'aura.auraInofensiva': 'Sua aura amaldiçoada é moldada para aparentar ser menor e menos intensa do que realmente é, dificultando até mesmo que te notem. Quando iniciar um combate, realize um teste de Feitiçaria contra a Atenção de todos os inimigos que poderiam o detectar pela sua energia amaldiçoada: você fica automaticamente escondido contra toda criatura cuja Atenção seja superada pelo resultado do seu teste. Estar escondido por meio desta aptidão segue as regras comuns de Furtividade, descritas na página 297. [Pré-Requisito: Presença 16]',
  'aura.auraExcessiva': 'Pode pagar 2 PE/rodada para receber resistência parcial a todos os danos (exceto alma) igual ao valor de redução de Aura Reforçada. [Pré: Aura Reforçada, Constituição 16, Nível 8]',
  'aura.enganacaoProjetada': 'Usando de agilidade e rapidez, você consegue projetar a sua aura antes de um ataque, criando uma ilusão de quando ele acontecerá. Quando atacar uma criatura, ela deve realizar um teste de resistência de astúcia (atributo principal da técnica), e caso falhe, você terá vantagem nesse ataque. Para cada ataque após o primeiro, no mesmo turno, você deve pagar 1 ponto de energia amaldiçoada para projetar a ilusão. [Pré-Requisito: Treinado em Enganação, Destreza 18 e Nível 4]',
  'aura.golpeComAura': 'Ao invés de simplesmente deixar a sua aura fluir com um aspecto específico, você coloca esse aspecto no seu próximo golpe, dificultando a resistência. Você pode gastar 1 ponto de energia para imbuir um golpe com uma aptidão de aura que force um teste de resistência: a criatura realiza o teste de resistência caso o ataque acerte, e a CD aumenta em um valor igual ao seu Nível de Aptidão em Aura. Caso seja uma aptidão de aura que cause dano, o dano é considerado após ataque. Não é possível utilizar Golpe com Aura em Feitiços',
  'aura.transferenciaDeAura': 'Utilizando da sua energia, você se torna capaz de transferir a sua aura para outra pessoa. Como uma ação bônus, você pode pagar 2 pontos de energia amaldiçoada e escolher uma criatura dentro de 9 metros para transferir uma Aptidão de Aura específica. Você escolhe qual aptidão deseja transferir, e a pessoa recebe os efeitos dela durante uma rodada. Você pode manter a aura transferida por mais rodadas, pagando 1 ponto de energia para cada rodada após a primeira.',
  'aura.auraLacerante': 'Sua aura é afiada, causando danos apenas com o contato. Você pode ativar sua aura lacerante por 1 rodada, como ação livre. Enquanto ativa, uma criatura que iniciar seu turno dentro de 3 metros de você deve realizar um teste de resistência de Fortitude (atributo principal da técnica). Em uma falha, ela recebe Xd6 + seu modificador do atributo principal de dano energético, onde X é o seu Nível de Aptidão em Aura. No Nível de Aptidão em Aura 3, o dado aumenta para d8; no nível 5, aumenta para d10.',
  'aura.auraMacabra': 'Maldita e vil, sua aura é macabra e perturba aqueles que estejam sendo afetados por ela. Toda criatura agressiva que começar um turno dentro de 1,5 metros de você precisa realizar um teste de resistência de vontade (atributo principal da técnica). Em uma falha, ela fica Abalada, podendo repetir o teste no próximo turno dela, deixando de estar Abalada em um sucesso. Como uma ação livre, você pode pagar 1 ponto de energia amaldiçoada para expandir esse alcance para 4,5 metros por 1 rodada. A partir do Nível de Aptidão em Aura 3, você inflige Amedrontado ao invés de Abalado.',
  'aura.auraMacica': 'Sua aura é tão densa que parece começar a tomar uma forma maciça, dificultando os inimigos a conseguirem realmente acertálo. Sua Defesa aumenta em um valor igual a seu Nível de Aptidão em Aura. [PréRequisito: Constituição 16]',
  'aura.auraMovedica': 'Você molda a sua aura para atrapalhar a movimentação em suas proximidades. Ao obter esta Aptidão, todo quadrado adjacente a você se torna terreno difícil. No Nível de Aptidão em Aura 2, todo quadrado dentro de 3 metros se torna terreno difícil; no Nível 4, aumenta para 4,5 metros e, no Nível 5, aumenta para 6 metros. A área afetada por esta aptidão não pode ser aumentada por Expandir Aura.',
  'aura.auraRedirecionada': 'Você descobre como imbuir parte da sua aura em um projétil ou arma de arremesso, conseguindo-o redirecionar caso erre. Você pode gastar 2 pontos de energia amaldiçoada para imbuir um projétil ou arma de arremesso antes de realizar um ataque: caso erre o ataque com um projétil ou arma imbuída, você pode realizar a rolagem de ataque outra vez, tendo como alvo uma criatura dentro de 6 metros do primeiro alvo, conforme o projétil ou arma é redirecionada. Além disso, a segunda rolagem de ataque recebe um bônus no acerto igual a 1 + metade do seu Nível de Aptidão em Aura. [PréRequisito: Destreza 16]',
  'aura.auraReforcada': 'Reforçando o fluxo da sua aura, você se torna capaz de pausar e anular uma parcela do dano que recebe fisicamente, tornando mais difícil de realmente atingir seu corpo. Você recebe redução contra danos físicos — cortes, perfurações e impactos — igual ao dobro do seu Nível de Aptidão em Aura.',
  'aura.casuloDeEnergia': `Evoluindo ao limite o fluxo da aura, você consegue a deixar tão densa e maciça que se torna um casulo protetivo. Ao obter essa habilidade você pode, como uma Ação Comum, formar um casulo de energia por 1 rodada, gastando 6 pontos de energia amaldiçoada. Enquanto o casulo estiver ativo, você recebe imunidade a dano cortante, perfurante e de impacto provindo de fontes mundanas (como armas ou quedas). Caso seja originário de técnica, você apenas recebe RD adicional igual ao dobro do seu Nível de Aptidão em Aura. [Pré-Requisito: Aura Impenetrável, Nível de Aptidão em Aura 5 e Nível 16]`,
  'aura.auraImpenetravel': 'Melhorando ainda mais o fluxo, você se torna capaz de transformar a sua aura em uma fortaleza impenetrável contra simples golpes físicos. Ao obter essa habilidade, você pode, como uma Ação Bônus, transformar a sua aura em impenetrável por 1 rodada, gastando 3 pontos de energia amaldiçoada. Enquanto sua aura estiver impenetrável, você recebe resistência a dano cortante, perfurante e de impacto. [Pré-Requisito: Aura Reforçada, Nível de Aptidão em Aura 3 e Nível 10]',

  /* NOVAS APTIDÕES DE AURA */
  'aura.pavorInstintivo': `Sua presença emana um terror que paralisa os seres vivos. Efeito: Criaturas que não sejam maldições e comecem o turno a 3 metros de você devem fazer um TR de Vontade. Em uma falha, ficam Lentas por 1 rodada. Se você tiver AU 3, elas ficam Imobilizadas em vez de Lentas. Custo: Passivo (ou 2 PE para dobrar o alcance por 1 rodada).`,
  'aura.mimetismoDeResiduos': `Você consegue camuflar sua aura para parecer um objeto inanimado ou um resíduo inofensivo. Efeito: Você recebe um bônus em testes de Furtividade igual ao seu Nível de Aptidão em Aura. Se gastar 3 PE, você pode se tornar invisível para sentidos baseados em energia amaldiçoada por uma cena, desde que não realize ações agressivas.`,
  'aura.auraCorrosiva': `Sua energia amaldiçoada é ácida e consome o que toca. Efeito: Sempre que uma criatura te acertar com um ataque corpo a corpo, ela recebe dano de ácido igual ao seu Nível de Aptidão em Aura. Objetos mundanos que toquem sua aura por mais de 1 rodada começam a se degradar.`,
  'aura.presencaEsmagadora': `A densidade da sua aura é tão grande que dificulta a respiração e o movimento ao seu redor. Efeito: A área a 4,5 metros de você é considerada Terreno Difícil para humanos. Além disso, projéteis mundanos disparados contra você através desta área têm desvantagem no acerto.`,

  /* CONTROLE E LEITURA */
  'controleELeitura.canalizarEmGolpe': 'Você se torna capaz de concentrar sua energia amaldiçoada em suas armas e golpes, assim potencializando ainda mais a capacidade destrutiva em troca de um gasto de energia. Como uma Ação de Movimento, você pode gastar uma quantidade de pontos de energia amaldiçoada igual a seu nível de aptidão em Controle e Leitura para adicionar dano: para cada ponto gasto, seu próximo ataque causa 1d6 de dano adicional. Essa habilidade funciona apenas por um ataque e não pode ser utilizada em Feitiços. Errar um ataque não consome esse uso.',
  'controleELeitura.canalizacaoAvancada': 'Você aperfeiçoa a prática de canalizar energia em golpes, conseguindo a realizar mais rapidamente e com mais poder. Canalizar energia em um golpe também pode ser feito como uma reação ao realizar um ataque, e o bônus passa de 1d6 para 1d8. A habilidade continua funcionando apenas por um ataque e não é consumida em um erro. [Pré-Requisito: Canalizar em Golpe, Nível de Aptidão em Controle e Leitura 2 e Nível 8]',
  'controleELeitura.canalizacaoMaxima': 'Você alcança o ápice da técnica de canalizar energia nos seus golpes, levando-a para um nível superior. Você pode gastar 1PE adicional para Canalizar em Golpe e o bônus por ponto gasto aumenta de 1d8 para 1d10. Além disso, você soma seu Nível de Aptidão em Aura ao total de dano concedido pela Aptidão. [Pré-Requisito: Canalização Avançada, Nível de Aptidão em Controle e Leitura 4 e Nível 16]',
  'controleELeitura.cobrirSe': 'Você se torna capaz de concentrar sua energia amaldiçoada em seu corpo, assim amenizando os impactos em troca de um consumo imediato de energia. Como uma Reação, quando receber dano, você pode gastar uma quantidade de PE igual a 2 + o dobro do seu CL para receber pontos de vida temporários: para cada ponto gasto, você recebe 4 PVs temporários. Estes PVs temporários são avulsos a outras fontes e não seguem o limite comum para PVs temporários, durando até o final do turno da criatura contra a qual você usou a Reação.',
  'controleELeitura.coberturaAvancada': 'Você desenvolve a sua capacidade de revestir e cobrir seu corpo com energia amaldiçoada, resistindo a golpes. Ao usar sua Reação para cobrir-se, cada ponto gasto passa a conceder 8 pontos de vida temporários. [Pré-Requisito: Cobrir-se, Nível de Aptidão em Controle e Leitura 2 e Nível 10]',
  'controleELeitura.estimuloMuscular': 'Você se torna proficiente em utilizar da energia para estimular e reforçar o seu corpo, apurando força e agilidade. Quando realizar uma ação de movimento ou uma ação com as perícias Acrobacia ou Atletismo você pode, como parte da mesma ação, utilizar energia para os seguintes estímulos: • Caso seja uma ação de movimento, você pode gastar 1 PE para aumentar a distância em um valor igual a metade do seu deslocamento. • Caso seja um teste (comum ou oposto), você pode gastar até uma quantidade de PE igual a seu Nível de Aptidão em Controle e Leitura, recebendo um bônus de +1 para cada PE gasto. O bônus dura até o começo do seu próximo turno. • Caso seja uma ação que empurre uma criatura ou arremesse um objeto (Desarmar ou Empurrar), você pode gastar 2 PE para aumentar a distância em um valor igual ao seu Nível de Aptidão em Controle e Leitura multiplicado por 1,5 metros. • Caso seja a ação de Pular, você pode gastar 1PE para dobrar a distância percorrida. Você só pode utilizar cada estímulo uma vez por rodada.',
  'controleELeitura.estimuloMuscularAvancado': 'Seu controle para imbuir os músculos com energia torna-se ainda mais apurado. Você passa a poder utilizar cada estímulo duas vezes por rodada e eles recebem as seguintes melhorias: • Caso gaste PE para aumentar seu deslocamento, você pode escolher gastar 2PE ao invés de 1PE para que ele seja aumentado em um valor igual ao seu Deslocamento total, ao invés de metade. • Caso gaste para receber bônus em um teste, cada PE gasto passa a somar +2 no teste. • Caso gaste para aprimorar uma ação de empurrar criatura ou arremessar objeto, a distância é aumentada em um valor igual ao seu Nível de Aptidão multiplicado por 3 metros. [PréRequisito: Estímulo Muscular, Nível de Aptidão]',
  'controleELeitura.expandirAura': 'Você se torna capaz de controlar bem a sua energia, incluindo a que compõe sua aura, podendo assim a expandir com uma descarga de energia. No seu turno, como uma ação livre, você pode gastar 2 pontos de energia amaldiçoada para expandir a sua aura, dobrando o alcance de todas as suas aptidões de aura passivas por uma rodada. Para cada rodada após a primeira, você deve pagar mais 1 ponto de energia para a manter expandida. [Pré-Requisito: Nível 6]',
  'controleELeitura.leituraDeAura': 'Compreendendo bem a energia e as propriedades que ela pode assumir em auras, você consegue ler auras e identificar os seus efeitos. Ao ver uma criatura que possua uma aura amaldiçoada, você pode realizar uma rolagem de Feitiçaria para tentar a ler e descobrir suas propriedades, cuja CD é igual a CD Amaldiçoada da criatura. Caso suceda no teste, você descobre quais as propriedades passivas e ativas da aura da criatura.',
  'controleELeitura.leituraRapidaDeEnergia': 'Treinando e se adaptando a ler rapidamente auras, você adquire uma maior capacidade de prever a próxima ação dos usuários de energia amaldiçoada, o que te favorece não só ofensivamente, mas defensivamente também. Você pode, como uma Ação de Movimento, realizar um teste de Percepção contra a CD Amaldiçoada de uma criatura, recebendo um bônus igual ao seu CL. Caso suceda, você não pode receber desvantagem ou prejuízos para acertar o inimigo por causa de aura e ignora aumentos de Defesa fornecidos por auras, até o final da cena',
  'controleELeitura.projetarEnergia': 'Ao invés de canalizar energia em um objeto, você a concentra e libera como um projétil explosivo. Você pode gastar uma quantidade de pontos de energia amaldiçoada igual 1 + seu nível de aptidão em Controle e Leitura e o transformar em um projétil, o qual você dispara como uma ação comum. Para cada ponto gasto, o projétil causará 1d10 de dano energético, somando o modificador do seu maior atributo no total. O alcance do projétil é igual a 9 metros + 1,5 metros x bônus de treinamento. Você pode escolher tanto fazer uma rolagem de ataque amaldiçoada (a qual não pode ser um crítico), ou forçar o alvo a realizar um teste de resistência de reflexos (maior atributo), anulando o dano em um sucesso',
  'controleELeitura.projecaoAvancada': 'Dominando a prática de concentrar e disparar projéteis a partir da sua energia, você eleva sua projeção. O dano causado por ponto gasto aumenta para 2d8, além de passar a somar o dobro do seu modificador ao total. Caso use como um ataque, você recebe +2 para acertar ou, caso force um teste de resistência, a dificuldade aumenta em 2. [Pré-Requisito: Projetar Energia, Nível de Aptidão em Controle e Leitura 2 e Nível 8]',
  'controleELeitura.projecaoMaxima': 'Você leva a prática de disparar energia projetada até o ápice dela, criando projéteis devastadores. O dano por ponto aumenta de 2d8 para 3d8. O bônus para acertar se torna +6 e o aumento na dificuldade do teste de resistência 4, além de reduzir o dano à metade ao invés de anular em um sucesso, ao escolher forçar um TR. [PréRequisito: Projeção Avançada, Nível de Aptidão em Controle e Leitura 4 e Nível 16]',
  'controleELeitura.projecaoDividida': 'Você descobre uma nova maneira de disparar sua energia projeta, dividindo-a em dois projéteis no meio do caminho. Ao realizar um disparo de energia contra um alvo, você pode pagar até metade da energia gasta no disparo para o duplicar como parte da mesma ação. A duplicata do projétil deve ter como alvo uma criatura dentro de 4,5 metros do alvo original e causa dano equivalente à quantidade de energia gasta nele, seguindo o cálculo padrão de Projetar Energia; o projétil duplicado sempre segue o método de Teste de Resistência da aptidão. [Pré-Requisito: Projeção Avançada, Nível de Aptidão em Controle e Leitura 3 e Nível 12]',
  'controleELeitura.punhoDivergente': 'Uma técnica peculiar de controle do fluxo da energia. O impacto de seus golpes diverge e se divide em dois momentos: ao acertar o golpe, e após um curto período de tempo. Ao acertar um ataque desarmado, você pode escolher causar apenas metade do dano, e guardar a outra metade para ser causada no turno seguinte. Esta aptidão não pode ser utilizada em um ataque que seja um raio negro, devido a aplicação extremamente rápida da energia. Caso escolha que o resto do dano seja causado no turno seguinte, a criatura que recebeu o ataque deve realizar um teste de resistência de Fortitude (maior atributo físico) e, caso falhe, o dano será causado como se o inimigo tivesse vulnerabilidade. Além disso, conforme maior a potência do primeiro golpe, mais difícil é se preparar para resistir ao segundo impacto: para cada 5 pontos de dano na primeira metade do dano, a CD aumenta em 1',
  'controleELeitura.rastreioAvancado': 'Você refina e amplia suas capacidades de detectar e rastrear energia amaldiçoada. Quando estiver em uma cena em que energia amaldiçoada tenha sido usada ou deixada (Feitiços, aptidões, presença de maldições), você consegue detectar imediatamente vestígios e, caso já conheça de quem eles originam, você descobre na hora. Caso não conheça, você pode realizar um teste de Investigação ou Percepção contra a CD Amaldiçoada de quem originou o vestígio e, em um sucesso, você percebe as características daquela energia (se é de um humano ou maldição, um período aproximado em que esteve lá e outros) e é capaz de seguir o rastro até onde ele acaba.',
  'controleELeitura.emocaoDaPetalaDecadente': `Uma arte secreta transmitida entre as três grandes famílias Jujutsu como uma contra medida para expansões de domínio, entretanto, esta não é sua única utilização. O usuário se cobre com energia e contra-ataca quando um ataque de acerto garantido fosse o acertar. Como uma reação a uma expansão de domínio ser ativada ou como uma ação bônus, você pode usar emoção da pétala decadente. Enquanto estiver com a aptidão ativa, sempre que você receber um acerto garantido físico de uma expansão de domínio, você pode gastar uma quantidade de pontos de energia igual ao nível de DOM da criatura que expandiu o domínio, se o fizer o acerto garantido é anulado. Esta aptidão é um efeito de Concentração. Caso uma criatura entre no seu alcance corpo a corpo ou você comece seu turno com uma criatura dentro desse mesmo alcance, como uma ação livre, você pode gastar 5PE para realizar um ataque corpo a corpo com sucesso garantido, sem a necessidade de um teste. Se utilizar a aptidão de forma ofensiva você não pode se proteger contra acertos garantidos até o começo do seu próximo turno. [PréRequisito: Nível 5, aprender de um dos Três Grandes Clãs (Zenin, Gojo ou Kamo), Cobrir-se e Nível de Aptidão em Controle e Leitura 3]`,
  'controleELeitura.concentrarAura': `Você consegue concentrar a sua aura em um único ponto, que é a sua arma, sacrificando as propriedades dela em troca de um segundo impacto. Como uma ação livre, você pode escolher por desabilitar uma certa quantidade de aptidões de aura passivas por 1 rodada. Para cada aptidão passiva desabilitada, após acertar um ataque desarmado ou com arma, o alvo recebe 1d8 de dano energético. Você pode desabilitar até uma quantidade de aptidões igual a 1 + seu Nível de Aptidão em Aura. O dano desta Aptidão não é aplicado em Feitiços.`,
  'controleELeitura.fluxoConstante': 'Tendo uma maior dominância sobre a energia reversa, você estabelece um fluxo contínuo dela no seu corpo, preservando-o e restaurando-o assim que sua integridade é reduzida. Assim sendo, você pode manter uma cura contínua: no começo do seu turno, você pode se curar com energia reversa seguindo as mesmas regras da cura básica, porém como uma ação livre. Caso não o faça, você pode se curar como reação ao ter sua vida reduzida. [Pré-Requisito: Energia Reversa, Nível de Aptidão em Energia Reversa 3 e Nível 12]',
  'controleELeitura.fluxoImparavel': 'Reduz a eficácia de tentativas de anular ou dispersar sua energia, tornando suas aptidões mais estáveis em combate.',

  /* NOVAS APTIDÕES DE CONTROLE E LEITURA */
  'controleELeitura.regeneracaoEspontanea': `Diferente dos humanos, seu corpo é feito de energia, permitindo curar feridas instantaneamente. Efeito: Como uma Ação Bônus, você pode gastar X PE para curar Xd8 + CL pontos de vida. Você pode usar esta aptidão mesmo se estiver com 0 PV, desde que não tenha sido exorcizado por energia amaldiçoada.`,
  'controleELeitura.morfologiaGrotesca': `Você pode alterar a forma do seu corpo para criar membros extras ou armas biológicas. Efeito: Gastando 2 PE, você pode aumentar seu alcance natural em 1,5 metros ou criar um ataque natural adicional (Dano 1d8 + Força) por uma cena. Com CL 3, você pode criar dois membros extras.`,
  'controleELeitura.disparoDeNucleo': `Você concentra sua essência em um disparo concentrado de energia pura. Efeito: Semelhante ao Projetar Energia, mas se você gastar o máximo de PE permitido pelo seu CL, o dado de dano aumenta para d12 e o ataque ignora RD mundana.`,
  'controleELeitura.sentidoDePredador': `Você lê o medo nas pessoas para prever seus movimentos. Efeito: Você recebe um bônus em Iniciativa e Percepção igual ao seu CL. Se o alvo estiver sob qualquer condição de medo (Abalado, Amedrontado), você tem vantagem em ataques contra ele.`,
  'controleELeitura.divisaoCelular': `Você pode desprender uma parte de si para criar uma pequena distração. Efeito: Gastando 5 PE, você cria uma "Mini-Maldição" com 1 PV e Defesa igual à sua. Ela age no seu turno e pode realizar a ação de Ajudar ou Flanquear. Ela dura até o final da cena ou até ser destruída.`,

  /* BARREIRAS */
  'barreiras.tecnicasDeBarreiras': `Você se torna capaz de erguer e manipular barreiras, as quais podem ser usadas para defender o usuário ou prender oponentes. Você pode criar, como uma Ação Comum, até 6 paredes ao seu redor, com cada parede custando 1 ponto de energia amaldiçoada. Cada parede erguida tem 1,5 metros de tamanho, e vida igual a 5 + seu nível de aptidão em Barreiras multiplicado por metade do seu nível de personagem. Podem servir tanto como obstáculo como uma maneira de prender seus inimigos. Você pode as manipular e mover usando outra ação comum. [Pré-Requisito: Nível de Aptidão em Barreira 1]`,
  'barreiras.paredesResistentes': `As paredes que você confecciona se tornam mais resistentes. Os pontos de vida de cada parede passam a ser 10 + seu nível de aptidão em Barreiras multiplicado pelo seu nível de personagem. [Pré-Requisito: Técnicas de Barreira, Nível de Aptidão em Barreira 2 e Nível 4]`,
  'barreiras.barreiraRapida': `Com treino e repetição, você se torna capaz de erguer barreiras de maneira ainda mais ágil. Erguer ou manipular barreiras se torna uma ação bônus. [Pré-Requisito: Técnicas de Barreira, Nível de Aptidão em Barreira 3 e Nível 6]`,
  'barreiras.cestaOcaDeVime': `Uma antiga e esotérica técnica amaldiçoada utilizada contra domínios, antes mesmo do Domínio Simples ser criado. Como ação bônus ou reação a uma expansão de domínio, você pode gastar 3 PE para criar um trançado de vime ao seu redor e receber os efeitos desta aptidão. Enquanto estiver com a Cesta Oca de Vime ativa, você não é afetado pelo efeito de acerto garantido de uma expansão de domínio. Esta aptidão usa de Concentração e possui Durabilidade igual ao seu Nível de BAR + 1. Sempre que falhar em um teste de concentração, a Durabilidade da sua Cesta Oca de Vime desce em 1. No inicio do seu turno, caso você deveria ter sido atingido por um Acerto Garantido, sua Cesta Oca de Vime perde 1 de durabilidade. No inicio do seu turno, você pode manter o selo desta aptidão, ocupando as suas duas mãos, ao fazer isso, a Cesta Oca de Vime não pode perder durabilidade por qualquer efeito que não seja a falha de concentração. Caso a Cesta Oca de Vime quebre, você recebe o efeito do Acerto Garantido instantaneamente. [Pré-Requisito: Ser de uma época onde ela era utilizada ou Mestre em História, Nível de Aptidão em Barreira 1 e Nível 5]`,
  'barreiras.cortina': `A cortina é uma técnica de barreira comum, sendo um grande campo de força negro que isola uma área específica, impossibilitando pessoas de fora de ver seu interior. Seu funcionamento básico é de ocultamento, mas podem ser postas condições que expandem sua utilidade. Ao criar uma cortina, você gasta 1 ponto de energia para cada 9 metros que a área dela irá cobrir, e não há um custo para mantêla. Você também pode colocar condições em uma cortina, ao criá-la, de acordo com as regras sobre cortinas. [Pré-Requisito: Técnicas de Barreira]`,

  /* NOVAS DESCRIÇÕES DE BARREIRA */
  'barreiras.barreiraOrganica': `Suas barreiras são feitas de carne e sangue amaldiçoado, sendo mais difíceis de transpassar. Efeito: Suas paredes de barreira recebem RD a danos físicos igual ao seu Nível de Aptidão em Barreira. Criaturas que toquem a barreira devem fazer um TR de Fortitude ou ficarão Envenenadas.`,
  'barreiras.veloDeSombras': `Uma barreira sutil que obscurece a visão de quem está fora. Efeito: Você cria uma barreira que não impede o movimento, mas concede Camuflagem Total para quem está dentro contra quem está fora. Custo: 4 PE.`,
  'barreiras.dominioDeCaca': `Você molda a barreira para permitir a entrada, mas impedir a saída. Efeito: Ao criar uma barreira, você pode definir que certas criaturas podem entrar livremente, mas para sair devem vencer um teste oposto de Atletismo ou Acrobacia contra sua CD Amaldiçoada.`,

  /* ENERGIA REVERSA */
  'energiaReversa.energiaReversa': `Você desenvolve a capacidade de produzir energia reversa, multiplicando a energia amaldiçoada com ela mesma, convertendo negativo em positivo. Você libera acesso às aptidões desta categoria, as quais usam pontos de energia reversa (PER), com um PER sendo equivalente a dois pontos de energia amaldiçoada. Sua capacidade básica é se curar: para cada ponto de energia reversa gasto, você se cura em 2d6, somando seu modificador de presença ou sabedoria ao total de cura. Nos níveis 10, 15 e 20, a cura aumenta em 1d6. Você pode gastar um máximo de pontos de energia reversa por vez igual a 1 + metade do seu nível de aptidão. Curarse dentro de combate é uma ação comum e você não pode usar essa habilidade para curar outras criaturas. [Pré-Requisito: Treinado em Feitiçaria, Nível de Aptidão em Controle e Leitura 3 e Nível 8]`,
  'energiaReversa.curaAmplificada': `Sua capacidade de cura é amplificada quando utilizando energia reversa. O dado da cura se torna d8 e você passa a somar o dobro do seu modificador de presença ou sabedoria. A quantidade máxima de pontos que podem ser gastos passa a ser igual a 1 + seu nível de aptidão. [Pré-Requisito: Energia Reversa, Nível de Aptidão em Energia Reversa 3 e Nível 12]`,
  'energiaReversa.fluxoConstante': `Tendo uma maior dominância sobre a energia reversa, você estabelece um fluxo contínuo dela no seu corpo, preservando-o e restaurando-o assim que sua integridade é reduzida. Assim sendo, você pode manter uma cura contínua: no começo do seu turno, você pode se curar com energia reversa seguindo as mesmas regras da cura básica, porém como uma ação livre. Caso não o faça, você pode se curar como reação ao ter sua vida reduzida. [Pré-Requisito: Energia Reversa, Nível de Aptidão em Energia Reversa 3 e Nível 12]`,
  'energiaReversa.regeneracaoAprimorada': `Aumentando seu domínio sobre a energia reversa, você se torna mais capaz de se regenerar com ela. Você pode, como uma ação comum, regenerar Ferimentos Complexos, gastando 8 pontos de energia reversa por ferimento. Entretanto, caso seja um desmembramento, só é possível regenerar membros que tenham sido perdidos há menos de um dia ou não tenham sido cicatrizados ainda (p.315). Ao utilizar a aptidão, pode-se gastar mais para recuperar diferentes membros e feridas com o mesmo custo inicial. Se possuir o membro em mãos, a ação diminui para Bônus e o custo para recuperar o membro se torna 3 PER, conforme você coloca o membro no lugar. Além disso, você pode remover os efeitos de um veneno ao gastar uma Ação Bônus e 4PER. Ao atingir Nível de Aptidão em Energia Reversa 5, você passa a poder gastar 10PER ao invés do normal para utilizar a aptidão como uma ação livre. Quando você regenerar uma ferida, você se cura no equivalente de metade dos PER gastos para isso (caso gaste 8 para regenerar, você se cura o equivalente de 4PER gastos na aptidão Energia Reversa). [Pré-Requisito: Cura Amplificada, Nível de Aptidão em Energia Reversa 4 e Nível 15]`,
  'energiaReversa.liberacaoDeEnergiaReversa': `Além de ser capaz de se curar com a energia reversa, você aprende como a liberar para curar outras pessoas, o que é mais complexo e difícil. Você se torna capaz de curar outras criaturas utilizando a habilidade Energia Reversa, desde que estejam dentro do seu alcance de toque. [Pré-Requisito: Energia Reversa e Nível 10]`,
  'energiaReversa.canalizarEmEnergiaReversa': `A energia reversa é nociva a maldições, então você se torna capaz de canalizá-la e usá-la de maneira agressiva. Como uma Ação de Movimento, você pode gastar uma quantidade de pontos de energia reversa igual ao seu bônus de treinamento para adicionar dano de energia reversa a um ataque: para cada ponto gasto, você causa 2d6 de dano de energia reversa adicional. Essa habilidade funciona apenas por um ataque, o qual deve ser contra uma maldição e não pode ser utilizada em Feitiços. Errar um ataque não consome esse uso. Não é possível utilizar Canalizar em Golpe e Canalizar Energia Reversa simultaneamente, podendo aplicar apenas um deles em um mesmo ataque. [Pré-Requisito: Liberação de Energia Reversa e Canalizar em Golpe]`,
  'energiaReversa.curaEmGrupo': `Ao invés de curar apenas uma criatura, você se torna capaz de projetar a energia reversa entre diferentes componentes de um grupo. Ao invés de decidir um alvo, você pode optar por realizar a rolagem de cura e dividir o total do resultado entre todas as criaturas dentro de um alcance igual a 4,5 + 1,5 para cada Nível de Aptidão em Energia Reversa. A quantidade máxima de pontos que podem ser gastos aumenta em 2. [Pré-Requisito: Liberação de Energia Reversa]`,

  /* ESPECIAIS */
  'especiais.raioNegro': `O raio negro - ou kokusen - é um fenômeno no jujutsu, onde o golpe de um feiticeiro é altamente amplificado devido a uma distorção no espaço que ocorre quando a energia amaldiçoada é aplicada 0.000001 segundos antes dele acertar. Quando um feiticeiro o acerta, sua energia brilha em negro e o poder destrutivo é maior. Usar o kokusen também aumenta a compreensão da energia amaldiçoada permanentemente. Todos os efeitos da habilidade são: • Compreensão Avançada. Após usar o kokusen pela primeira vez, a sua compreensão sobre a energia amaldiçoada se expande. Seu máximo de energia amaldiçoada aumenta em um valor igual ao seu nível de personagem e o seu Nível de Aptidão em Aura aumenta em 1. Ao subir de nível, o aumento de energia é atualizado. • Raio Negro. Usar o Kokusen não é algo consciente, ocorrendo apenas em certos momentos. Quando tirar 20 em uma rolagem de ataque corpo-a-corpo, o seu golpe é coberto por raios negros, utilizando o Kokusen. Um golpe com Kokusen causa dano adicional igual a metade do total obtido na rolagem do dano (1.5x). O Dano Após Ataque é aplicado após o Kokusen. Além disso, ele ignora qualquer tipo de resistência ou redução de danos. • Estado de Consciência Absoluta. Após usar os raios negros, um feiticeiro adentra em um estado de foco, onde torna-se mais fácil acertar golpes, extraindo 120% de seu potencial. Durante 1 rodada, após conseguir um kokusen, o valor necessário para o kokusen reduzirá em um. Caso acerte outro kokusen, a duração será renovada e o valor necessário reduzirá novamente. Ele pode ser reduzido uma quantidade de vezes igual a metade do seu Nível de Aptidão em Controle e Leitura. [Pré-Requisito: Nível de Aptidão em Controle e Leitura 3, Força ou Destreza 16 e Nível 10]`,
  'especiais.abencoadoPelasFaiscasNegras': `Embora o raio negro seja algo incontrolável, você se foca tanto nisso que parece começar a conseguir cativar as faíscas negras, as quais te abençoam. Você passa a usar o kokusen, por padrão, em um 19 e em um 20 no dado. Ao estar em Estado de Consciência Absoluta, você pode reduzir o valor necessário para Kokusen 1 vez a mais. Além disso, após acertar um kokusen, você recebe um bônus igual a metade do seu Nível de Aptidão em Controle e Leitura em jogadas de ataque e o nível total de aptidão em rolagens de dano pelo resto da cena. [Pré-Requisito: Raio Negro, Nível de Aptidão em Controle e Leitura 4, Nível de Aptidão em Aura 3 e Nível 15]`,
  'especiais.dominioSimples': `Conhecido originalmente como o “Domínio dos Fracos”, o Domínio Simples ergue uma barreira ao redor do usuário juntamente de seu domínio, neutralizando os efeitos e Acerto Garantido de uma expansão. Você pode, com uma Reação contra a expansão de um domínio ou como Ação Bônus no seu turno, gastar 5 PE e criar uma esfera de X metros de raio a sua volta (onde X é igual a: 1,5m + Nível de DOM x 1,5 metros). Você e toda criatura dentro do Domínio Simples não são afetados pelo Acerto Garantido e os efeitos de ambiente de um domínio. Esta aptidão usa de Concentração e possui Y de Durabilidade (onde Y é igual ao seu Nível de BAR + 1). Sempre que falhar em um teste de concentração, a Durabilidade de seu domínio simples desce em 1. No inicio do seu turno, caso você deveria ter sido atingido por um acerto garantido, seu Domínio Simples perde 1 de durabilidade. Toda vez que seu Domínio Simples perder durabilidade, ele também tem sua área deteriorada em 1,5m. Caso a Durabilidade ou A Área do Domínio sejam deterioradas a 0, o Domínio Simples quebra, fazendo você e todos dentro receber o Acerto Garantido instantaneamente. [Pré-Requisito: Nível de Aptidão em Barreira 1 e Nível 5]`,
  'especiais.reversaoDeTecnica': `Em um processo complexo, você passa a ser capaz de utilizar energia reversa para abastecer a sua técnica, possibilitando assim um efeito contrário ao padrão e com maior potência. Quando obtiver um novo Feitiço, você pode escolher criar uma Reversão de Técnica no lugar: uma Reversão tem o seu custo aumentado em um valor igual ao nível do Feitiço e deve, também, ser criada como algo que reverte o conceito da sua técnica (o Vermelho, Reversão de Técnica do Ilimitado, empurra ao invés de puxar). Ao obter esta aptidão, você recebe um Feitiço adicional, a qual obrigatoriamente deve ser uma reversão. [Pré-Requisito: Energia Reversa e Nível 12]`,
  'especiais.tecnicaMaxima': `Dentre os feiticeiros jujutsu, existe a possibilidade de levar o potencial da sua técnica ao máximo, criando uma habilidade definitiva a partir dela. É uma arte suprema, com grande complexidade e necessidade de conhecimento sobre a própria técnica. Ao obter esta habilidade, você se torna capaz de criar uma Técnica Máxima: você recebe um novo Feitiço o qual, caso você possua acesso apenas aos de Nível 4, utiliza os valores de Nível 5 para sua criação e, quando receber acesso ao Nível 5, sua Técnica Máxima passa a seguir os valores próprios de uma. Uma Técnica Máxima custa 25 PE e, após ser usada, você deve esperar uma quantidade de rodadas igual a 6 – metade do seu Bônus de Treinamento para poder utilizá-la novamente. [Pré-Requisito: Mestre em Feitiçaria, Capacidade de Conjurar Feitiços Nível 4]`,

  /* APTIDÕES ESPECIAIS ADICIONADAS */
  'especiais.fisiologiaGrauEspecial': `Seu corpo de energia atingiu um estado de refinamento tão alto que você é considerado um desastre natural ambulante. Efeito: Você recebe imunidade a dano de fontes mundanas (não amaldiçoadas) e Resistência a Danos (RD) passiva contra danos físicos igual ao seu Bônus de Treinamento. Além disso, seu máximo de Energia Amaldiçoada aumenta em um valor igual ao dobro do seu nível de personagem. Como uma Reação ao receber dano de uma técnica, você pode gastar 2 PE para somar seu modificador de Constituição à sua RD até o início do seu próximo turno. [Pré-Requisito: Constituição 20 e Nível 12].`,
  'especiais.nucleoEnergiaErrante': `Diferente dos humanos, sua consciência e "ponto vital" não estão fixos. Você pode mover seu núcleo pelo corpo para evitar golpes fatais. Efeito: Você se torna imune a acertos críticos. Sempre que um ataque fosse te deixar com 0 PV, você pode realizar um TR de Fortitude (CD igual a 10 ou metade do dano sofrido, o que for maior). Em um sucesso, você fica com 1 PV em vez disso. Alternativamente, você pode gastar uma quantidade de PE igual a 1/4 do dano recebido para sobreviver com 1 PV sem realizar o teste. [Pré-Requisito: Nível 14].`,
  'especiais.instintoPredadorAmaldicoado': `Você desenvolveu um sentido que detecta o medo e a hesitação, permitindo reagir antes mesmo do oponente agir. Efeito: Você recebe um bônus de +5 em Iniciativa. Além disso, você pode realizar uma Reação adicional por rodada, desde que essa reação seja usada para realizar um ataque de oportunidade ou usar uma aptidão contra uma criatura que esteja sob uma condição de medo (Abalado, Amedrontado, etc.). [Pré-Requisito: Percepção Treinada, Presença 18 e Nível 10].`,
  'especiais.consumoDeEssenciaCanibalismo': `Você pode devorar os resquícios de outras maldições ou a energia de feiticeiros para se fortalecer. Efeito: Como uma Ação Comum, você pode tentar consumir uma criatura adjacente que esteja com 0 PV ou Incapacitada. Se for uma maldição, você recupera PE igual ao nível dela x 2. Se for um humano, você recupera PV igual ao modificador de Constituição dele + seu Nível de Personagem. Você pode usar esta habilidade um número de vezes igual ao seu Bônus de Treinamento por descanso longo. [Pré-Requisito: Força 18 e Nível 10].`,
  'especiais.manifestacaoDeDesastre': `Sua técnica inata é tão poderosa que ela começa a vazar para o mundo real, alterando o ambiente ao seu redor. Efeito: Como uma Ação Bônus, você pode ativar sua aura de desastre gastando 5 PE. Ela dura por 1 minuto (Concentração). Enquanto ativa, criaturas inimigas em um raio de 15 metros recebem 2d6 de dano de um tipo elemental ligado à sua técnica no início de seus turnos (TR de Fortitude reduz à metade) e têm desvantagem em testes de resistência contra seus feitiços desse elemento. [Pré-Requisito: Mestre em Feitiçaria e Nível 15].`,
  'especiais.votoRestricaoFormaVerdadeira': `Você libera uma forma grotesca e devastadora, ignorando as limitações da forma humana. Efeito: Como uma Ação Bônus, você entra em sua Forma Verdadeira por uma quantidade de rodadas igual ao seu Bônus de Treinamento. Nesta forma, você recebe Vantagem em todos os ataques, seus ataques causam um dado de dano extra do mesmo tipo da arma/golpe e sua Defesa aumenta em 4. Ao final do efeito, você perde 10 PE e fica Lento e Enfraquecido por 1 minuto. [Pré-Requisito: Nível 12].`,
  'especiais.ressonanciaMedoColetivo': `Você se alimenta do medo das massas, tornando-se mais forte quanto mais pessoas estiverem apavoradas ao seu redor. Efeito: Para cada criatura em um raio de 18 metros que esteja sob a condição Amedrontado ou Abalado, você recebe +1d6 de dano em seus feitiços (máximo de bônus igual ao seu Bônus de Treinamento). Se houver pelo menos 3 criaturas amedrontadas na área, a CD de seus feitiços aumenta em +2. [Pré-Requisito: Presença 20 e Nível 14].`,
  'especiais.regeneracaoCelularViolenta': `Sua capacidade de cura é tão agressiva que seu corpo reconstrói membros em segundos. Efeito: Enquanto você estiver com menos da metade dos seus PV máximos, você regenera PV igual ao seu modificador de Constituição + Bônus de Treinamento no início de cada um de seus turnos. Regenerar um membro decepado custa 5 PE e pode ser feito como uma ação livre no seu turno. [Pré-Requisito: Constituição 22 e Nível 16].`,
  'especiais.dominioDeIntrusao': `Você aprendeu a "vazar" seu domínio para dentro de outras barreiras, interferindo em territórios alheios. Efeito: Quando você estiver dentro de uma Expansão de Domínio ou Domínio Simples de outra criatura, você pode gastar 10 PE para forçar um teste oposto de Feitiçaria. Se vencer, você anula o Acerto Garantido do oponente contra você e anula quaisquer bônus de atributo que o domínio conceda a ele por 1 rodada. Além disso, você ignora a barreira do domínio para fins de mirar seus próprios feitiços. [Pré-Requisito: Nível de Personagem 15 e possuir uma Expansão de Domínio].`,
  'especiais.transcendenciaAmaldicoada': `Você atingiu o ápice do que significa ser uma maldição, transcendendo os limites da morte e da forma. Efeito: Se você for morto (exorcizado), sua essência não desaparece imediatamente. Você permanece como um "Resíduo Consciente" por 1d4 dias. Durante esse tempo, você pode tentar possuir um objeto ou um cadáver humano (TR de Vontade do alvo contra sua CD Amaldiçoada). Se tiver sucesso, você renasce com metade do seu nível original, mantendo suas memórias e técnica inata. [Pré-Requisito: Nível 20].`,
  /* DOMÍNIO */
  'dominio.revestimentoDeDominio': `Você se cobre com um domínio fino, o qual não possui nenhum Feitiço imbuído, assim conseguindo neutralizar técnicas ao derramá-las no espaço do revestimento. Você pode gastar 5 PE e uma Ação Bônus, ou reação ao ser alvo dos efeitos de um Feitiço, para a ativar o Revestimento: Enquanto ele estiver ativo você pode gastar 5 PE para sustentar o efeito no início dos seus turnos. Com o Revestimento de Domínio ativo, você reduz o dano de efeitos de técnicas ofensivas que te afetarem em um valor igual ao seu nível de personagem. Essa redução não pode ser ignorada. Caso a Técnica seja de um nível menor ou igual a metade do Nível de DOM, arredondado para cima, ela é completamente anulada. Este efeito apenas se aplica para Feitiços que não afetem diretamente a sua energia amaldiçoada, como Boogie Woogie ou Nulificação. Ademais, seus golpes também anulam completamente qualquer efeito passivo, ativo, sustentado ou duradouro proveniente de Feitiço, desde que tal efeito seja de um nível do qual você consiga anular, com o funcionamento básico sendo considerado como um Feitiço de primeiro nível. Enquanto estiver com o Revestimento de Domínio ativo você não pode utilizar ou estar sob o efeito de qualquer Feitiço. [Pré-Requisito: Nível de Aptidão em Controle e Leitura 3, Nível de Aptidão em Domínio 1 e Nível 10]`,
  'dominio.anularTecnica': `Você aprimora o seu domínio simples para ser efetivo não só contra expansões de domínio, mas contra técnicas amaldiçoadas no geral, conseguindo anulálas se usado rapidamente. Quando você for alvo ou submetido a um Feitiço, você pode usar sua reação para tentar anulála; você só pode tentar anular um Feitiço que seja de um nível que você tem ou teria acesso a. Você gasta uma quantidade de energia amaldiçoada igual à que foi usada para conjurar a habilidade, e realiza um teste Feitiçaria contra a Feitiçaria de quem usou o Feitiço. Caso a habilidade que você deseja anular seja em área, nenhuma das criaturas submetidas sofrem o efeito, desde que você a anule. Por ser algo cansativo e complexo, você pode usar essa habilidade uma quantidade de vezes igual ao Nível de Aptidão em Domínio, por descanso longo. [Pré-Requisito: Domínio Simples, Nível de Aptidão em Domínio 3 e Nível 8]`,
  'dominio.expansaoDeDominioIncompleta': `Iniciando-se na parte mais complexa do Jujutsu, você passa a ser capaz de expandir o seu domínio interno, embora ainda de maneira incompleta. Como uma ação comum, desde que tenhas as duas mãos livres, você pode pagar 15PE para expandir seu domínio incompleto, o qual se espalha por uma área igual a 4,5 metros multiplicado pelo seu bônus de treinamento, adaptando-se também ao ambiente ao seu redor. Enquanto estiver com a expansão ativa, certos efeitos são aplicados, os quais devem ser montados de acordo com o Guia de Criação de Expansões de Domínio. Uma expansão de domínio incompleta dura, por padrão, uma quantidade de rodadas igual a 1 + seu nível de aptidão em domínio. [PréRequisito: Nível de Aptidão em Domínio 1 e Nível 8]`,
  'dominio.expansaoDeDominioCompleta': `Aperfeiçoando na técnica da expansão, alcança-se um patamar superior, conseguindo fechar uma barreira e prender seus alvos dentro dela. Como uma ação comum, desde que tenhas as duas mãos livres, você pode pagar 20PE para expandir seu domínio completo, o qual cria uma área esférica de 9 metros. Enquanto estiver com a expansão ativa, certos efeitos são aplicados, os quais devem ser montados de acordo com o Guia de Criação de Expansões de Domínio. Uma expansão de domínio completa dura, por padrão, uma quantidade de rodadas igual a 3 + seu nível de aptidão em domínio. [Pré-Requisito: Técnicas de Barreira, Expansão de Domínio Incompleta, Nível de Aptidão em Barreira e Domínio 3 e Nível 10]`,
  'dominio.acertoGarantido': `Você alcança o ápice das técnicas de domínio, conseguindo usar o acerto garantido, que define uma expansão de domínio letal. Ao obter esta aptidão, você pode adicionar o efeito Acerto Garantido em sua expansão de domínio, o qual não conta para o máximo, imbuindo sua técnica nas barreiras criadas. O funcionamento do Acerto Garantido deve ser elaborado de acordo com o guia de criação de domínios. Adicionar acerto garantido em uma expansão completa aumenta o seu custo em 5 pontos de energia amaldiçoada. [Pré-Requisito: Expansão de Domínio Completa, Treinamento em Feitiçaria, Nível de Aptidão em Barreira e Domínio 4 e Nível 14]`,
  'dominio.expansaoDeDominioSemBarreiras': `Assim como conter água sem um recipiente ou desenhar no céu sem uma tela, existe uma forma de expandir um domínio que exige um controle sobre a energia amaldiçoada extremo, sendo possível apenas para os mais talentosos e habilidosos. A expansão sem barreiras possui os mesmos efeitos e custo de uma expansão completa com acerto garantido, mas não levanta barreiras, tendo um alcance superior para o acerto garantido em troca, o qual pode até mesmo superar as barreiras de outras expansões de domínio, atacando-os por fora. [PréRequisito: Acerto Garantido, Mestre em Feitiçaria, Nível de Aptidão em Barreira e Domínio 5, e Nível 20]`,

  /* NOVAS APTIDÕES DE DOMÍNIO */
  'dominio.ecoDoMedo': `Seu domínio amplifica os traumas dos oponentes. Efeito: Dentro do seu Domínio (Incompleto ou Completo), a CD para resistir a condições de medo aumenta em um valor igual ao seu Nível de Aptidão em Domínio.`,
  'dominio.consumoDeEssencia': `Você se alimenta da energia gasta pelos seus inimigos dentro do seu domínio. Efeito: Sempre que um inimigo gastar PE dentro do seu domínio, você recupera 1 PV para cada 2 PE gastos por ele.`,
  'dominio.ambienteMutavel': `O terreno do seu domínio obedece à sua vontade. Efeito: Como uma Ação Livre no seu turno, você pode alterar o terreno dentro do domínio para criar cobertura, terreno difícil ou elevações de até 3 metros.`,
};

// Texto completo de fallback (usado se não houver descrição específica)
export const APTIDOES_DESC_COMPLETA = `Descrição completa das Aptidões disponível no manual do sistema.`;

/* DESCRIÇÕES - FISIOLOGIA AMALDIÇOADA */
export const APTIDOES_FISIOLOGIA_DESCR = {
  'fisiologiaAmaldicoada.nucleoMovel': `Sua consciência não está presa ao cérebro, mas sim a um núcleo de energia que se move pelo corpo. Efeito: Você se torna imune a acertos críticos de armas mundanas. Se sofrer um acerto crítico de uma arma amaldiçoada, você pode gastar 4 PE para transformar o crítico em um acerto normal.`,
  'fisiologiaAmaldicoada.parasitismoEnergetico': `Você pode se prender a um hospedeiro para drenar sua vida. Efeito: Ao realizar uma manobra de Agarrar com sucesso, você pode gastar 2 PE por turno para causar 1d6 de dano de energia e recuperar a mesma quantidade em PV.`,
  'fisiologiaAmaldicoada.vozDasSombras': `Sua voz ressoa diretamente na mente das vítimas, causando confusão. Efeito: Como uma Ação Comum, você força um alvo a 9 metros a fazer um TR de Vontade. Em uma falha, o alvo fica Confuso por 1 rodada. Custo: 3 PE.`,
  'fisiologiaAmaldicoada.adaptacaoReativa': `Seu corpo de energia se molda para resistir ao que o fere. Efeito: Sempre que receber dano de um tipo específico (Fogo, Frio, etc.), você pode usar sua Reação e 3 PE para ganhar RD 5 contra esse tipo de dano até o final da cena.`
,
  'fisiologiaAmaldicoada.almaMaldita': `Sua alma é impregnada com energia amaldiçoada, assumindo um aspecto maldito e difícil de se alterar. Efeito: Quando uma criatura for causar dano na sua alma, esse dano é reduzido à metade antes do teste de Integridade; a partir do Nível 15, ele é anulado. Esta habilidade funciona 2 vezes por dia, 3 vezes no Nível 6, 4 vezes no Nível 12 e 5 vezes no Nível 18.`,
  'fisiologiaAmaldicoada.anatomiaIncompreensivel': `O seu corpo tem uma forma que é difícil de compreender. Efeito: Você tem 25% de chance (resultado "1" em 1d4) de ignorar o dano adicional de um ataque crítico ou um ataque furtivo. No Nível 15, essa chance torna-se 50% (resultado "1 ou 2" em 1d4).`,
  'fisiologiaAmaldicoada.armaNatural': `Com uma fisionomia estranha, você possui garras, dentes afiados, cauda ou outro apêndice corporal próprio para ataques. Efeito: Você recebe um ataque natural que causa 1d8 de dano Cortante, Perfurante ou de Impacto com os traços Fineza e Enérgica. Esta arma natural conta como um ataque desarmado e se beneficia de efeitos que afetariam ataques desarmados. Caso seu dano desarmado seja superior ao da arma natural, ao invés disso aumente o seu dano desarmado em 1 nível.`,
  'fisiologiaAmaldicoada.articulacoesExtensas': `Suas juntas são mais longas, ou suas garras são estendidas, aumentando a distância com que pode atacar. Efeito: O alcance dos seus ataques corpo a corpo aumenta em 1,5 metros.`,
  'fisiologiaAmaldicoada.bracosExtras': `Seu corpo possui um par de braços adicionais. Efeito: Você recebe +2 em testes de Prestidigitação e, se tiver pelo menos duas mãos livres, aplica esse bônus em testes de Atletismo. Recebe um par adicional de mãos, permitindo equipar dois equipamentos de uma mão ou um equipamento de duas mãos adicional, assim como agarrar duas criaturas e outros benefícios à discrição do Narrador.`,
  'fisiologiaAmaldicoada.capacidadeVoo': `No seu corpo repousa uma capacidade de voo, que com um estímulo de energia se torna ativa. Efeito: Como uma ação livre, você pode gastar 1 ponto de energia para transformar seu Deslocamento de Caminhada em Deslocamento de Voo por uma rodada.`,
  'fisiologiaAmaldicoada.carapacaMutante': `Uma carapaça cobre o seu corpo, sendo uma mutação bizarra, mas resistente. Efeito: Você recebe Redução de Dano contra danos físicos igual ao seu Bônus de Treinamento; no Nível 10, você recebe resistência a um tipo de dano físico à sua escolha (após escolhida não pode ser mudada).`,
  'fisiologiaAmaldicoada.corpoEspecializado': `Seu corpo se desenvolve de maneira a possuir um foco. Efeito: Escolha uma perícia: você recebe um bônus de 1d4 nessa perícia.`,
  'fisiologiaAmaldicoada.desenvolvimentoExagerado': `Seu corpo se desenvolve de maneira exagerada, ultrapassando o formato e o porte padrão. Efeito: Você aumenta sua categoria de tamanho em 1 e recebe 1 ponto de vida adicional por nível.`,
  'fisiologiaAmaldicoada.devoradorDeEnergia': `Sendo envolvido com a própria energia, você pode a devorar quando resiste a uma habilidade originada dela. Efeito: Quando passar em um teste de resistência para resistir a um Feitiço, você recebe 1 ponto de energia temporário cumulativo.`,
  'fisiologiaAmaldicoada.instintoSanguinario': `Em sua essência há um instinto por sangue e violência. Efeito: Você adiciona o seu Bônus de Treinamento na sua Iniciativa; enquanto em uma cena de combate, você também adiciona seu Bônus de Treinamento na sua Atenção.`,
  'fisiologiaAmaldicoada.olhosSombrios': `Seus olhos guardam escuridão, sendo sombrios por natureza e aguçados. Efeito: Você recebe Visão no Escuro. Além disso, você se torna treinado em Percepção e recebe um bônus de +2 em rolagens com a perícia. No Nível 12 você passa a ignorar completamente efeitos de escuridão leve e total.`,
  'fisiologiaAmaldicoada.pernasExtras': `No seu corpo cresce um par de pernas extras. Efeito: Seu deslocamento aumenta em 4,5 metros e você passa a ignorar terreno difícil que esteja no solo.`,
  'fisiologiaAmaldicoada.presencaNefasta': `Com um semblante vil, a sua própria presença é nefasta. Efeito: Toda criatura hostil, ao vê-lo pela primeira vez, deve realizar um teste de resistência de Vontade contra sua CD Amaldiçoada. Em uma falha, ela fica Amedrontada por uma rodada. Em um sucesso, ela fica Abalada por uma rodada.`,
  'fisiologiaAmaldicoada.sangueToxico': `O seu sangue é tóxico, capaz de corroer o que entra em contato com ele. Efeito: Sempre que sofrer dano de um ataque corpo a corpo, o atacante perde PV igual ao seu modificador de Constituição.`
};

// Insere as descrições da fisiologia no objeto principal de descrições para compatibilidade
if (typeof APTIDOES_DESCRICOES === 'object') {
  for (const k of Object.keys(APTIDOES_FISIOLOGIA_DESCR)) {
    APTIDOES_DESCRICOES[k] = APTIDOES_FISIOLOGIA_DESCR[k];
  }
}
